In [1]:
# Join rainfall and njhomeprice tables from RDS
# Dependencies and Setup
#
import pandas as pd
import os
import datetime
import re
import numpy as np
import psycopg2
from sqlalchemy import create_engine

In [2]:
# Setup connection to Postgres RDS
engine = create_engine('postgresql+psycopg2://postgres:finalgroup5@finalprojectgroup5.c1jelrjhbrlm.us-east-1.rds.amazonaws.com:5432/postgres')

In [17]:
# Join rainfall and njhomeprice
query = ("SELECT * from njhomeprice"
     )
#new_df = pysqldf("SELECT a.*, b.list3 from df1 as a INNER JOIN df2 as b ON a.key=b.key;")
njhomeprice_df=pd.read_sql(query,engine)

In [18]:
njhomeprice_df

,index,zipcode,State,CITY,CountyName,SizeRank,eom_date,month,year,avghomeprice_month,price_drop
0,0,08701,NJ,Lakewood Township,Ocean County,83,2000-01-31,1,2000,170574.0,
1,1,08753,NJ,Toms River,Ocean County,202,2000-01-31,1,2000,141372.0,
2,2,07002,NJ,Bayonne,Hudson County,227,2000-01-31,1,2000,172571.0,
3,3,07087,NJ,Union City,Hudson County,363,2000-01-31,1,2000,126530.0,
4,4,08759,NJ,Manchester Township,Ocean County,573,2000-01-31,1,2000,121255.0,
...,...,...,...,...,...,...,...,...,...,...,...
124811,124811,08555,NJ,Roosevelt,Monmouth County,25206,2022-05-31,5,2022,411741.0,
124812,124812,08323,NJ,Greenwich Township,Cumberland County,25226,2022-05-31,5,2022,225175.0,
124813,124813,08350,NJ,Buena Vista Township,Atlantic County,25635,2022-05-31,5,2022,291296.0,
124814,124814,08346,NJ,Buena Vista Township,Atlantic County,25777,2022-05-31,5,2022,262059.0,
124815,124815,08212,NJ,Cape May Point,Cape May County,26351,2022-05-31,5,2022,1314938.0,